insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (1, 'Jaxspan', 'Rupiah', '$0.06');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (2, 'Wordware', 'Pound', '$4.94');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (3, 'Bluejam', 'Dollar', '$4.37');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (4, 'Kaymbo', 'Yuan Renminbi', '$1.17');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (5, 'Skimia', 'Kuna', '$0.29');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (6, 'Feedbug', 'Franc', '$0.21');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (7, 'Gigashots', 'Peso', '$8.69');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (8, 'Meeveo', 'Krone', '$3.83');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (9, 'Edgeblab', 'Yuan Renminbi', '$8.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (10, 'Twitterworks', 'Peso', '$2.59');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (11, 'Feedspan', 'Franc', '$1.12');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (12, 'Yambee', 'Euro', '$4.34');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (13, 'Mynte', 'Zloty', '$4.23');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (14, 'Youspan', 'Rupiah', '$7.02');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (15, 'Twitternation', 'Kuna', '$8.16');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (16, 'Devcast', 'Ruble', '$0.58');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (17, 'Babbleblab', 'Ruble', '$3.13');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (18, 'DabZ', 'Rupiah', '$3.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (19, 'Browsedrive', 'Yen', '$0.48');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (20, 'Voonix', 'Quetzal', '$0.04');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (21, 'Meezzy', 'Kwacha', '$0.74');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (22, 'Mita', 'Yuan Renminbi', '$6.93');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (23, 'Oyondu', 'Boliviano', '$9.41');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (24, 'Myworks', 'Rupee', '$5.11');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (25, 'Topiczoom', 'Rupiah', '$6.06');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (26, 'Topicblab', 'Euro', '$5.29');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (27, 'Browsetype', 'Rupiah', '$0.72');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (28, 'Riffpedia', 'Yuan Renminbi', '$8.01');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (29, 'Kwinu', 'Rupiah', '$9.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (30, 'Demimbu', 'Peso', '$3.64');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (31, 'Yoveo', 'Yuan Renminbi', '$4.88');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (32, 'Livetube', 'Litas', '$5.81');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (33, 'Zoomzone', 'Franc', '$6.86');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (34, 'Abata', 'Euro', '$4.61');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (35, 'Browseblab', 'Sol', '$0.17');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (36, 'Avavee', 'Dirham', '$9.38');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (37, 'Flashpoint', 'Zloty', '$5.12');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (38, 'Lajo', 'Dirham', '$7.29');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (39, 'Wikivu', 'Yuan Renminbi', '$8.45');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (40, 'Katz', 'Yuan Renminbi', '$0.36');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (41, 'Wordpedia', 'Euro', '$8.41');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (42, 'Dynabox', 'Baht', '$0.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (43, 'Zoozzy', 'Rupiah', '$2.18');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (44, 'Jetpulse', 'Rial', '$5.07');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (45, 'Realcube', 'Euro', '$4.78');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (46, 'Blogspan', 'Dram', '$1.94');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (47, 'Ooba', 'Hryvnia', '$4.51');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (48, 'Yozio', 'Peso', '$2.05');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (49, 'Zoomdog', 'Peso', '$6.45');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (50, 'Browsedrive', 'Rupiah', '$3.16');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (51, 'Midel', 'Peso', '$5.10');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (52, 'Kwimbee', 'Real', '$8.11');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (53, 'Yozio', 'Yuan Renminbi', '$4.74');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (54, 'Voonix', 'Euro', '$8.24');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (55, 'Zoovu', 'Yen', '$5.14');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (56, 'Ozu', 'Real', '$7.69');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (57, 'Fatz', 'Real', '$0.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (58, 'Pixonyx', 'Peso', '$5.69');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (59, 'Buzzster', 'Dollar', '$2.06');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (60, 'Avamm', 'Sol', '$2.00');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (61, 'Linkbridge', 'Peso', '$6.78');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (62, 'Rhycero', 'Peso', '$7.46');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (63, 'Tanoodle', 'Franc', '$7.51');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (64, 'Trudeo', 'Marka', '$6.39');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (65, 'Minyx', 'Yuan Renminbi', '$7.24');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (66, 'Yodel', 'Lev', '$2.99');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (67, 'Brightbean', 'Dollar', '$0.25');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (68, 'Innotype', 'Yuan Renminbi', '$9.20');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (69, 'Twimbo', 'Zloty', '$8.60');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (70, 'Twimbo', 'Real', '$8.27');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (71, 'Minyx', 'Ariary', '$8.40');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (72, 'Jabbersphere', 'Yuan Renminbi', '$2.54');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (73, 'Jaxspan', 'Euro', '$0.45');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (74, 'Camimbo', 'Yen', '$6.47');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (75, 'Jayo', 'Rupiah', '$1.25');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (76, 'Jaloo', 'Euro', '$4.61');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (77, 'Topicware', 'Hryvnia', '$7.82');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (78, 'Demivee', 'Yen', '$5.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (79, 'Feedspan', 'Yuan Renminbi', '$4.27');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (80, 'Linkbuzz', 'Baht', '$5.25');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (81, 'Kwilith', 'Zloty', '$3.33');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (82, 'Zazio', 'Koruna', '$2.33');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (83, 'Yodel', 'Zloty', '$4.34');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (84, 'Bubblebox', 'Peso', '$6.67');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (85, 'Photofeed', 'Yuan Renminbi', '$1.80');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (86, 'Agimba', 'Ruble', '$8.93');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (87, 'Browsebug', 'Lev', '$4.12');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (88, 'Skyble', 'Yuan Renminbi', '$4.05');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (89, 'Chatterpoint', 'Euro', '$8.73');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (90, 'Devpoint', 'Real', '$8.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (91, 'Voolia', 'Shilling', '$5.51');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (92, 'Aimbo', 'Dollar', '$0.97');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (93, 'Omba', 'Lev', '$9.39');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (94, 'Avamm', 'Dollar', '$5.03');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (95, 'Eazzy', 'Euro', '$6.28');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (96, 'Dabvine', 'Real', '$5.50');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (97, 'Mynte', 'Euro', '$4.57');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (98, 'Midel', 'Real', '$9.80');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (99, 'Dabtype', 'Rupiah', '$5.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (100, 'Photobug', 'Rupiah', '$9.19');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (101, 'Flashspan', 'Dong', '$7.11');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (102, 'Dabjam', 'Krona', '$4.80');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (103, 'Browsezoom', 'Sol', '$7.14');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (104, 'Youspan', 'Ruble', '$2.08');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (105, 'Pixoboo', 'Somoni', '$4.28');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (106, 'Edgewire', 'Yuan Renminbi', '$0.27');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (107, 'Midel', 'Yen', '$9.78');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (108, 'Jaxspan', 'Kwacha', '$2.42');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (109, 'Mydo', 'Peso', '$7.52');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (110, 'Teklist', 'Litas', '$4.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (111, 'Skivee', 'Yuan Renminbi', '$4.96');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (112, 'Oba', 'Peso', '$2.55');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (113, 'Dabvine', 'Ruble', '$6.67');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (114, 'Tanoodle', 'Peso', '$5.62');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (115, 'Yakijo', 'Ruble', '$0.59');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (116, 'Shuffletag', 'Shilling', '$1.14');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (117, 'Dynazzy', 'Yuan Renminbi', '$1.48');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (118, 'Brainlounge', 'Koruna', '$9.73');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (119, 'Skinix', 'Bolivar', '$8.62');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (120, 'Jayo', 'Baht', '$3.92');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (121, 'Eayo', 'Yen', '$2.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (122, 'Yambee', 'Yuan Renminbi', '$1.04');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (123, 'Roodel', 'Yuan Renminbi', '$5.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (124, 'Yakijo', 'Euro', '$3.85');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (125, 'Tagfeed', 'Rupiah', '$9.86');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (126, 'Kazu', 'Yuan Renminbi', '$0.16');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (127, 'Latz', 'Yuan Renminbi', '$0.64');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (128, 'Vinder', 'Euro', '$3.02');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (129, 'Meetz', 'Peso', '$7.88');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (130, 'Camimbo', 'Pound', '$5.75');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (131, 'Devpulse', 'Krona', '$6.00');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (132, 'Yozio', 'Yuan Renminbi', '$4.82');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (133, 'Chatterpoint', 'Peso', '$9.31');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (134, 'Edgewire', 'Rupiah', '$4.24');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (135, 'Dynava', 'Rupiah', '$7.46');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (136, 'Vitz', 'Peso', '$2.75');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (137, 'Demimbu', 'Real', '$7.05');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (138, 'Jamia', 'Peso', '$9.09');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (139, 'Tagfeed', 'Euro', '$0.49');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (140, 'Voomm', 'Yuan Renminbi', '$3.64');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (141, 'Skaboo', 'Ruble', '$2.91');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (142, 'Jabberbean', 'Rupiah', '$6.61');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (143, 'Tazzy', 'Krona', '$6.14');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (144, 'Shuffletag', 'Euro', '$9.85');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (145, 'Aibox', 'Euro', '$8.71');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (146, 'DabZ', 'Ruble', '$9.04');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (147, 'Rhybox', 'Zloty', '$5.59');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (148, 'Twimbo', 'Dirham', '$7.09');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (149, 'Gigashots', 'Franc', '$0.40');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (150, 'Devcast', 'Franc', '$0.91');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (151, 'Topicstorm', 'Franc', '$4.08');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (152, 'Mycat', 'Euro', '$5.34');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (153, 'Jayo', 'Dollar', '$7.45');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (154, 'Quire', 'Rupiah', '$4.47');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (155, 'Tagopia', 'Hryvnia', '$8.64');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (156, 'Quimm', 'Yuan Renminbi', '$4.47');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (157, 'Avamba', 'Koruna', '$4.09');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (158, 'Jaxbean', 'Zloty', '$1.17');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (159, 'Minyx', 'Dollar', '$1.13');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (160, 'Podcat', 'Rupiah', '$0.08');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (161, 'Thoughtstorm', 'Peso', '$0.88');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (162, 'Abatz', 'Ruble', '$5.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (163, 'Devshare', 'Afghani', '$3.94');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (164, 'Zoozzy', 'Euro', '$4.65');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (165, 'Twitternation', 'Sol', '$3.63');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (166, 'Avavee', 'Rupiah', '$4.02');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (167, 'Pixope', 'Krona', '$4.62');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (168, 'Brainsphere', 'Rupiah', '$4.89');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (169, 'Kayveo', 'Real', '$8.92');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (170, 'Jetwire', 'Rupiah', '$5.36');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (171, 'Fiveclub', 'Rupiah', '$5.84');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (172, 'Tagchat', 'Rupiah', '$6.69');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (173, 'Jaxspan', 'Yuan Renminbi', '$3.36');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (174, 'Tavu', 'Rupiah', '$7.31');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (175, 'Demivee', 'Euro', '$1.04');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (176, 'Skyba', 'Yuan Renminbi', '$8.73');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (177, 'Tazz', 'Pula', '$4.31');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (178, 'Mita', 'Ruble', '$2.89');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (179, 'Realbuzz', 'Krone', '$6.40');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (180, 'Gabcube', 'Krone', '$6.39');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (181, 'Linktype', 'Peso', '$8.75');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (182, 'Browsebug', 'Hryvnia', '$2.31');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (183, 'Trunyx', 'Ruble', '$2.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (184, 'Dablist', 'Peso', '$1.61');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (185, 'Midel', 'Euro', '$6.09');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (186, 'Demivee', 'Rupiah', '$1.17');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (187, 'Gabvine', 'Yen', '$9.31');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (188, 'Yakijo', 'Euro', '$9.49');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (189, 'Oloo', 'Euro', '$3.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (190, 'Thoughtstorm', 'Krona', '$2.78');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (191, 'Twimm', 'Peso', '$3.65');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (192, 'Trupe', 'Yen', '$0.70');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (193, 'Jabberstorm', 'Peso', '$5.06');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (194, 'Realmix', 'Baht', '$6.98');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (195, 'Fivespan', 'Euro', '$2.13');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (196, 'Shuffletag', 'Yen', '$5.41');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (197, 'Npath', 'Yuan Renminbi', '$3.73');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (198, 'Bubblebox', 'Yuan Renminbi', '$1.91');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (199, 'Yoveo', 'Ruble', '$2.72');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (200, 'Devcast', 'Boliviano', '$1.42');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (201, 'Meeveo', 'Euro', '$1.20');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (202, 'Omba', 'Lev', '$8.34');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (203, 'Cogilith', 'Yuan Renminbi', '$1.77');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (204, 'Zoombeat', 'Dollar', '$9.50');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (205, 'Linkbuzz', 'Rupiah', '$1.29');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (206, 'Oyondu', 'Peso', '$3.02');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (207, 'Trupe', 'Sol', '$5.06');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (208, 'Meembee', 'Yuan Renminbi', '$9.30');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (209, 'Photolist', 'Rupiah', '$5.36');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (210, 'Zoomlounge', 'Real', '$7.68');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (211, 'Oyondu', 'Yuan Renminbi', '$0.96');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (212, 'Babblestorm', 'Ruble', '$5.95');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (213, 'Babbleset', 'Yuan Renminbi', '$6.14');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (214, 'Photofeed', 'Rupiah', '$2.17');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (215, 'Topiczoom', 'Yuan Renminbi', '$5.05');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (216, 'Skibox', 'Rupiah', '$9.36');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (217, 'Skyndu', 'Peso', '$6.00');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (218, 'Trunyx', 'Dinar', '$7.57');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (219, 'Digitube', 'Som', '$6.99');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (220, 'Vimbo', 'Peso', '$2.48');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (221, 'Zoonoodle', 'Krona', '$0.22');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (222, 'Zoonoodle', 'Yuan Renminbi', '$8.37');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (223, 'Tekfly', 'Peso', '$6.50');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (224, 'Jamia', 'Euro', '$8.40');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (225, 'Jazzy', 'Sol', '$2.18');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (226, 'Eabox', 'Rupiah', '$0.22');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (227, 'Viva', 'Peso', '$3.90');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (228, 'Twimm', 'Rupiah', '$7.20');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (229, 'Eimbee', 'Peso', '$8.23');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (230, 'Zooxo', 'Bolivar', '$9.81');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (231, 'Roombo', 'Balboa', '$0.88');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (232, 'Skynoodle', 'Yuan Renminbi', '$8.80');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (233, 'Dynava', 'Krona', '$4.40');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (234, 'Demizz', 'Koruna', '$2.22');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (235, 'Zoozzy', 'Sol', '$5.66');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (236, 'Yodel', 'Rupiah', '$2.24');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (237, 'Jabbertype', 'Yuan Renminbi', '$8.68');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (238, 'Brightdog', 'Boliviano', '$6.91');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (239, 'Zazio', 'Yuan Renminbi', '$1.83');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (240, 'Voonyx', 'Naira', '$7.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (241, 'Oyoyo', 'Litas', '$6.24');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (242, 'Browsebug', 'Naira', '$7.59');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (243, 'Eimbee', 'Euro', '$5.41');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (244, 'Oyondu', 'Yuan Renminbi', '$8.40');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (245, 'Bubblemix', 'Peso', '$0.55');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (246, 'Cogibox', 'Peso', '$1.63');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (247, 'Eazzy', 'Real', '$7.35');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (248, 'Skiba', 'Shilling', '$9.65');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (249, 'Zoonder', 'Rupiah', '$5.83');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (250, 'Kaymbo', 'Nakfa', '$8.54');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (251, 'Oozz', 'Euro', '$1.44');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (252, 'Browsecat', 'Koruna', '$2.39');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (253, 'Jetpulse', 'Yuan Renminbi', '$8.30');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (254, 'Babbleopia', 'Real', '$7.66');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (255, 'Vimbo', 'Franc', '$4.56');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (256, 'Mynte', 'Dinar', '$4.33');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (257, 'Photofeed', 'Euro', '$0.73');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (258, 'Yotz', 'Yuan Renminbi', '$7.43');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (259, 'Trudeo', 'Rupiah', '$1.45');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (260, 'Vidoo', 'Real', '$9.16');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (261, 'Innotype', 'Somoni', '$3.61');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (262, 'Tagtune', 'Real', '$6.58');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (263, 'Zoombox', 'Sol', '$0.32');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (264, 'Yakitri', 'Won', '$6.71');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (265, 'Flashpoint', 'Dollar', '$7.29');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (266, 'Kamba', 'Ringgit', '$7.10');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (267, 'Rhynoodle', 'Rupiah', '$4.89');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (268, 'Skivee', 'Krona', '$9.57');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (269, 'Kimia', 'Ruble', '$9.12');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (270, 'Devshare', 'Zloty', '$9.70');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (271, 'Ntag', 'Euro', '$6.24');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (272, 'Blogpad', 'Euro', '$1.96');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (273, 'Ntags', 'Yuan Renminbi', '$4.86');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (274, 'Lazzy', 'Dollar', '$9.99');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (275, 'Talane', 'Peso', '$9.12');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (276, 'Abatz', 'Sol', '$9.80');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (277, 'Camimbo', 'Yuan Renminbi', '$4.52');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (278, 'Jabbertype', 'Franc', '$9.27');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (279, 'Rhycero', 'Yuan Renminbi', '$8.74');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (280, 'Oloo', 'Rupiah', '$4.72');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (281, 'Jazzy', 'Yuan Renminbi', '$4.03');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (282, 'Oyoloo', 'Dollar', '$0.48');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (283, 'Realmix', 'Yuan Renminbi', '$1.60');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (284, 'Latz', 'Yuan Renminbi', '$0.08');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (285, 'Realcube', 'Dollar', '$6.15');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (286, 'Dynabox', 'Zloty', '$2.52');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (287, 'Riffpath', 'Lek', '$5.87');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (288, 'Babblestorm', 'Peso', '$5.95');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (289, 'Thoughtmix', 'Won', '$8.54');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (290, 'Nlounge', 'Yuan Renminbi', '$3.34');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (291, 'Skiba', 'Euro', '$2.70');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (292, 'Twimbo', 'Rupiah', '$4.31');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (293, 'Ntags', 'Peso', '$2.03');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (294, 'Flashdog', 'Yuan Renminbi', '$5.72');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (295, 'Twimbo', 'Krona', '$7.10');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (296, 'Linkbuzz', 'Yuan Renminbi', '$9.63');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (297, 'Meevee', 'Hryvnia', '$0.39');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (298, 'Realbridge', 'Rupiah', '$0.78');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (299, 'Zoomcast', 'Bolivar', '$9.73');
insert into user_company (USERID, COMPANYNAME, CURR, MONEY) values (300, 'Voonder', 'Rupiah', '$4.41');
