create table Products (
	id INT,
	name TEXT,
	price DECIMAL(20,2),
	stock INT
);
insert into Products (id, name, price, stock) values (84, 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna', 367481.44, 1668531);
insert into Products (id, name, price, stock) values (18, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 1777115.23, 7879658);
insert into Products (id, name, price, stock) values (86, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 8256105.99, 7981213);
insert into Products (id, name, price, stock) values (28, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', 580344.7, 8193405);
insert into Products (id, name, price, stock) values (68, 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam', 9240.41, 4598218);
insert into Products (id, name, price, stock) values (55, 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', 6678139.81, 27712);
insert into Products (id, name, price, stock) values (68, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 5304713.94, 7932453);
insert into Products (id, name, price, stock) values (91, 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', 8469647.95, 5642729);
insert into Products (id, name, price, stock) values (32, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 9509781.04, 4491889);
insert into Products (id, name, price, stock) values (81, 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 1414336.79, 2505672);
insert into Products (id, name, price, stock) values (68, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 7309944.62, 8360006);
insert into Products (id, name, price, stock) values (28, 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus', 5269510.27, 2621540);
insert into Products (id, name, price, stock) values (11, 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac', 2173862.58, 6782107);
insert into Products (id, name, price, stock) values (43, 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', 7937652.66, 4717763);
insert into Products (id, name, price, stock) values (76, 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor', 6332847.84, 4574560);
insert into Products (id, name, price, stock) values (53, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', 7873002.53, 5888198);
insert into Products (id, name, price, stock) values (10, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus', 60746.24, 410864);
insert into Products (id, name, price, stock) values (60, 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi', 144868.41, 562904);
insert into Products (id, name, price, stock) values (98, 'id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', 865665.83, 5670615);
insert into Products (id, name, price, stock) values (7, 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 2613995.83, 2382397);
insert into Products (id, name, price, stock) values (93, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 1981516.66, 9455948);
insert into Products (id, name, price, stock) values (51, 'sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 4154751.04, 3450970);
insert into Products (id, name, price, stock) values (32, 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum', 9502943.66, 1618811);
insert into Products (id, name, price, stock) values (41, 'morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede', 5125362.18, 7218660);
insert into Products (id, name, price, stock) values (75, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in', 8937798.48, 5054598);
insert into Products (id, name, price, stock) values (33, 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 8551722.7, 5230701);
insert into Products (id, name, price, stock) values (63, 'semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 997747.37, 9690621);
insert into Products (id, name, price, stock) values (68, 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', 5693138.64, 4042813);
insert into Products (id, name, price, stock) values (7, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', 3379244.31, 4589092);
insert into Products (id, name, price, stock) values (39, 'arcu sed augue aliquam erat volutpat in congue etiam justo', 7546366.13, 4205671);
insert into Products (id, name, price, stock) values (61, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas', 7617055.2, 3033213);
insert into Products (id, name, price, stock) values (37, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 878719.49, 6373948);
insert into Products (id, name, price, stock) values (54, 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', 4645848.53, 6541562);
insert into Products (id, name, price, stock) values (89, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 3052793.01, 2786436);
insert into Products (id, name, price, stock) values (46, 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 7998594.2, 4124897);
insert into Products (id, name, price, stock) values (8, 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 7972401.29, 314659);
insert into Products (id, name, price, stock) values (25, 'at feugiat non pretium quis lectus suspendisse potenti in eleifend', 5829632.8, 6406433);
insert into Products (id, name, price, stock) values (90, 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque', 2236643.49, 3971010);
insert into Products (id, name, price, stock) values (80, 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 5640876.56, 164778);
insert into Products (id, name, price, stock) values (43, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 3294033.58, 6060843);
insert into Products (id, name, price, stock) values (44, 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris', 7600081.45, 6288327);
insert into Products (id, name, price, stock) values (82, 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo', 1897178.92, 3989016);
insert into Products (id, name, price, stock) values (35, 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 4528430.22, 5816817);
insert into Products (id, name, price, stock) values (46, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui', 7101081.77, 690051);
insert into Products (id, name, price, stock) values (57, 'felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 572311.95, 5044308);
insert into Products (id, name, price, stock) values (91, 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras', 2627490.72, 5866255);
insert into Products (id, name, price, stock) values (72, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', 4079562.15, 114183);
insert into Products (id, name, price, stock) values (88, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis', 3506197.63, 6006534);
insert into Products (id, name, price, stock) values (83, 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac', 9972894.05, 7230212);
insert into Products (id, name, price, stock) values (70, 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 6666433.65, 922013);
insert into Products (id, name, price, stock) values (17, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', 4500392.73, 1421667);
insert into Products (id, name, price, stock) values (35, 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante', 8184664.85, 9068465);
insert into Products (id, name, price, stock) values (49, 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 3581101.0, 3680477);
insert into Products (id, name, price, stock) values (15, 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id', 1394031.85, 3144089);
insert into Products (id, name, price, stock) values (68, 'amet nulla quisque arcu libero rutrum ac lobortis vel dapibus', 4311845.58, 9572554);
insert into Products (id, name, price, stock) values (17, 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', 6945574.02, 1474323);
insert into Products (id, name, price, stock) values (28, 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis', 1818155.91, 1494410);
insert into Products (id, name, price, stock) values (18, 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 9938341.47, 2221555);
insert into Products (id, name, price, stock) values (42, 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien', 2816866.75, 3797410);
insert into Products (id, name, price, stock) values (6, 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', 7456852.78, 4212411);
insert into Products (id, name, price, stock) values (92, 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', 6073352.85, 6076718);
insert into Products (id, name, price, stock) values (12, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', 3347764.94, 6332093);
insert into Products (id, name, price, stock) values (8, 'sed tristique in tempus sit amet sem fusce consequat nulla nisl', 1406593.65, 8724441);
insert into Products (id, name, price, stock) values (21, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', 422620.6, 1415700);
insert into Products (id, name, price, stock) values (21, 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac', 6153373.91, 8974261);
insert into Products (id, name, price, stock) values (2, 'odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', 7104009.72, 3289726);
insert into Products (id, name, price, stock) values (87, 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 7091457.21, 5526305);
insert into Products (id, name, price, stock) values (84, 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', 8929752.33, 6392893);
insert into Products (id, name, price, stock) values (40, 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi', 1740534.16, 1241561);
insert into Products (id, name, price, stock) values (45, 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 504205.2, 788919);
insert into Products (id, name, price, stock) values (46, 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 6108246.95, 4553830);
insert into Products (id, name, price, stock) values (74, 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 5445808.49, 6784110);
insert into Products (id, name, price, stock) values (94, 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', 7651694.68, 2901282);
insert into Products (id, name, price, stock) values (18, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 1329839.74, 5313841);
insert into Products (id, name, price, stock) values (50, 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 7075415.7, 9691243);
insert into Products (id, name, price, stock) values (83, 'congue eget semper rutrum nulla nunc purus phasellus in felis', 6171026.59, 4799531);
insert into Products (id, name, price, stock) values (68, 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 5127651.67, 8150077);
insert into Products (id, name, price, stock) values (43, 'aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 6621750.44, 3650588);
insert into Products (id, name, price, stock) values (41, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', 3239092.3, 1528758);
insert into Products (id, name, price, stock) values (96, 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec', 4304591.98, 1230155);
insert into Products (id, name, price, stock) values (46, 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 1773394.17, 6316892);
insert into Products (id, name, price, stock) values (32, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 4907852.59, 7657531);
insert into Products (id, name, price, stock) values (61, 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 6142811.31, 2964036);
insert into Products (id, name, price, stock) values (42, 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', 3071789.72, 788971);
insert into Products (id, name, price, stock) values (68, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla', 9295403.0, 97304);
insert into Products (id, name, price, stock) values (32, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur', 4130784.21, 9400904);
insert into Products (id, name, price, stock) values (69, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis', 8394141.29, 937923);
insert into Products (id, name, price, stock) values (38, 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', 3774188.28, 5513165);
insert into Products (id, name, price, stock) values (75, 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 2798232.96, 5603958);
insert into Products (id, name, price, stock) values (54, 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 8653588.22, 1233828);
insert into Products (id, name, price, stock) values (75, 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 3573538.51, 5013045);
insert into Products (id, name, price, stock) values (84, 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci', 2832741.2, 6080740);
insert into Products (id, name, price, stock) values (67, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 1560761.15, 4857694);
insert into Products (id, name, price, stock) values (51, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 6087858.99, 4364425);
insert into Products (id, name, price, stock) values (89, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit', 5264685.45, 9149406);
insert into Products (id, name, price, stock) values (54, 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum', 2312030.25, 7320837);
insert into Products (id, name, price, stock) values (22, 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat', 3512759.09, 9281875);
insert into Products (id, name, price, stock) values (29, 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 6802903.43, 3691339);
insert into Products (id, name, price, stock) values (90, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 5492739.19, 1461362);
insert into Products (id, name, price, stock) values (25, 'odio cras mi pede malesuada in imperdiet et commodo vulputate', 6166243.67, 8515690);
insert into Products (id, name, price, stock) values (23, 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 7125667.09, 5673785);
insert into Products (id, name, price, stock) values (19, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel', 7750452.94, 7971822);
insert into Products (id, name, price, stock) values (44, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', 4858310.25, 6980847);
insert into Products (id, name, price, stock) values (83, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', 7662206.94, 1658744);
insert into Products (id, name, price, stock) values (8, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 1521253.33, 5294061);
insert into Products (id, name, price, stock) values (31, 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 2953706.5, 6780454);
insert into Products (id, name, price, stock) values (21, 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', 8663928.22, 8950690);
insert into Products (id, name, price, stock) values (75, 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', 429229.15, 6290646);
insert into Products (id, name, price, stock) values (22, 'in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', 6881336.56, 5149625);
insert into Products (id, name, price, stock) values (64, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id', 4317193.5, 2199183);
insert into Products (id, name, price, stock) values (71, 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', 4844076.73, 8202116);
insert into Products (id, name, price, stock) values (20, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', 9662784.76, 855110);
insert into Products (id, name, price, stock) values (56, 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 1846805.82, 1997369);
insert into Products (id, name, price, stock) values (63, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 7682982.9, 5742183);
insert into Products (id, name, price, stock) values (19, 'commodo placerat praesent blandit nam nulla integer pede justo lacinia', 982113.57, 4721490);
insert into Products (id, name, price, stock) values (44, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', 4791114.26, 3383341);
insert into Products (id, name, price, stock) values (22, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent', 621146.02, 9280729);
insert into Products (id, name, price, stock) values (32, 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac', 7803286.92, 834723);
insert into Products (id, name, price, stock) values (17, 'suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', 6616364.13, 9007218);
insert into Products (id, name, price, stock) values (17, 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', 4543236.59, 5845977);
insert into Products (id, name, price, stock) values (31, 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', 9496277.46, 9592473);
insert into Products (id, name, price, stock) values (37, 'est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 9106524.66, 3565700);
insert into Products (id, name, price, stock) values (23, 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in', 1797211.49, 7229854);
insert into Products (id, name, price, stock) values (82, 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', 3872395.3, 4668480);
insert into Products (id, name, price, stock) values (85, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 736218.83, 7384393);
insert into Products (id, name, price, stock) values (48, 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 4359370.21, 2777130);
insert into Products (id, name, price, stock) values (67, 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 7729933.8, 3844740);
insert into Products (id, name, price, stock) values (45, 'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 5659251.71, 7819806);
insert into Products (id, name, price, stock) values (78, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat', 5855436.47, 2709585);
insert into Products (id, name, price, stock) values (7, 'magna at nunc commodo placerat praesent blandit nam nulla integer', 9319876.15, 8685307);
insert into Products (id, name, price, stock) values (66, 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur', 5891701.02, 298644);
insert into Products (id, name, price, stock) values (89, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 8588939.96, 3731340);
insert into Products (id, name, price, stock) values (67, 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est', 7708266.48, 3103836);
insert into Products (id, name, price, stock) values (62, 'consequat lectus in est risus auctor sed tristique in tempus sit amet', 1258378.63, 8123877);
insert into Products (id, name, price, stock) values (50, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', 4454947.53, 6066346);
insert into Products (id, name, price, stock) values (57, 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus', 5286998.18, 6762677);
insert into Products (id, name, price, stock) values (50, 'suscipit nulla elit ac nulla sed vel enim sit amet', 7739895.43, 2080108);
insert into Products (id, name, price, stock) values (82, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', 8425526.01, 4671348);
insert into Products (id, name, price, stock) values (72, 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus', 6119026.9, 8129171);
insert into Products (id, name, price, stock) values (66, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 3839645.44, 5387747);
insert into Products (id, name, price, stock) values (88, 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 6277286.96, 9869248);
insert into Products (id, name, price, stock) values (87, 'sit amet lobortis sapien sapien non mi integer ac neque duis', 1971083.09, 2748403);
insert into Products (id, name, price, stock) values (24, 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 691342.81, 7828791);
insert into Products (id, name, price, stock) values (98, 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', 7227059.76, 7847490);
insert into Products (id, name, price, stock) values (46, 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 2831135.93, 1025871);
insert into Products (id, name, price, stock) values (42, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio', 5885335.39, 2776800);
insert into Products (id, name, price, stock) values (88, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 7826527.59, 7498425);
insert into Products (id, name, price, stock) values (3, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 126933.7, 2385934);
insert into Products (id, name, price, stock) values (76, 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 7996004.79, 1560171);
insert into Products (id, name, price, stock) values (90, 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 794983.65, 4286524);
insert into Products (id, name, price, stock) values (14, 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 5467831.02, 972357);
insert into Products (id, name, price, stock) values (25, 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in', 6775104.3, 1401070);
insert into Products (id, name, price, stock) values (70, 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', 4720986.11, 5867327);
insert into Products (id, name, price, stock) values (22, 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 5236750.0, 8780148);
insert into Products (id, name, price, stock) values (59, 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo', 1552257.69, 6781663);
insert into Products (id, name, price, stock) values (64, 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', 8307673.69, 3265112);
insert into Products (id, name, price, stock) values (48, 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum', 4343421.51, 1304707);
insert into Products (id, name, price, stock) values (14, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis', 8400984.84, 7158156);
insert into Products (id, name, price, stock) values (5, 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', 919592.27, 8939931);
insert into Products (id, name, price, stock) values (16, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 636116.9, 9722367);
insert into Products (id, name, price, stock) values (70, 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at', 7441338.22, 7663793);
insert into Products (id, name, price, stock) values (70, 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 4516301.86, 3388630);
insert into Products (id, name, price, stock) values (64, 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas', 2106323.88, 1041204);
insert into Products (id, name, price, stock) values (24, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 6944727.16, 9168102);
insert into Products (id, name, price, stock) values (70, 'volutpat dui maecenas tristique est et tempus semper est quam pharetra', 5595912.41, 6079189);
insert into Products (id, name, price, stock) values (31, 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo', 5756074.28, 8724292);
insert into Products (id, name, price, stock) values (97, 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor', 4604741.0, 6366606);
insert into Products (id, name, price, stock) values (71, 'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 1108872.33, 6350285);
insert into Products (id, name, price, stock) values (20, 'consequat lectus in est risus auctor sed tristique in tempus sit', 3078245.89, 728068);
insert into Products (id, name, price, stock) values (57, 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', 5436198.59, 5389198);
insert into Products (id, name, price, stock) values (29, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 6329055.09, 1344938);
insert into Products (id, name, price, stock) values (13, 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 3721367.02, 3750958);
insert into Products (id, name, price, stock) values (57, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo', 1348276.37, 251293);
insert into Products (id, name, price, stock) values (83, 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 9492790.05, 3011587);
insert into Products (id, name, price, stock) values (6, 'eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 7875635.2, 7427788);
insert into Products (id, name, price, stock) values (34, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 5156928.9, 1112405);
insert into Products (id, name, price, stock) values (27, 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', 6781163.91, 5551638);
insert into Products (id, name, price, stock) values (52, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 4179159.54, 7998700);
insert into Products (id, name, price, stock) values (6, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 7037067.33, 8538735);
insert into Products (id, name, price, stock) values (37, 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 292195.66, 6603373);
insert into Products (id, name, price, stock) values (94, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet', 7553206.25, 9094601);
insert into Products (id, name, price, stock) values (16, 'suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 1308590.63, 5545850);
insert into Products (id, name, price, stock) values (77, 'lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 7937230.88, 9697093);
insert into Products (id, name, price, stock) values (69, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', 1612676.26, 5845591);
insert into Products (id, name, price, stock) values (4, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi', 5180132.49, 9087567);
insert into Products (id, name, price, stock) values (97, 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc', 486358.23, 2061588);
insert into Products (id, name, price, stock) values (37, 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet', 5174384.91, 6339839);
insert into Products (id, name, price, stock) values (72, 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices', 8605137.83, 1453631);
insert into Products (id, name, price, stock) values (63, 'ligula vehicula consequat morbi a ipsum integer a nibh in quis', 5952804.03, 8520680);
insert into Products (id, name, price, stock) values (74, 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse', 2500918.28, 8462685);
insert into Products (id, name, price, stock) values (61, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', 6253122.58, 4527227);
insert into Products (id, name, price, stock) values (43, 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 4890737.29, 7433114);
insert into Products (id, name, price, stock) values (94, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 71854.15, 9304656);
insert into Products (id, name, price, stock) values (4, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 8598064.49, 4544435);
insert into Products (id, name, price, stock) values (41, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', 9100374.76, 4112997);
insert into Products (id, name, price, stock) values (75, 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 1317933.08, 5417521);
insert into Products (id, name, price, stock) values (80, 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 8522232.44, 5904858);
insert into Products (id, name, price, stock) values (89, 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 1139180.58, 9919197);
insert into Products (id, name, price, stock) values (18, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', 2032581.17, 9141292);
insert into Products (id, name, price, stock) values (25, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices', 8694916.67, 42689);
insert into Products (id, name, price, stock) values (87, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', 3674580.09, 1034890);
insert into Products (id, name, price, stock) values (83, 'non interdum in ante vestibulum ante ipsum primis in faucibus', 9972604.8, 1619506);
insert into Products (id, name, price, stock) values (71, 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse', 9878141.16, 4226404);
insert into Products (id, name, price, stock) values (76, 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 3340088.65, 4989587);
insert into Products (id, name, price, stock) values (75, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 9050795.41, 1030972);
insert into Products (id, name, price, stock) values (63, 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla', 2472605.32, 9358117);
insert into Products (id, name, price, stock) values (52, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 6547169.47, 6204078);
insert into Products (id, name, price, stock) values (74, 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 343356.62, 5306127);
insert into Products (id, name, price, stock) values (61, 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', 9499365.34, 5165959);
insert into Products (id, name, price, stock) values (36, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', 4294186.32, 554014);
insert into Products (id, name, price, stock) values (24, 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 200354.52, 8202241);
insert into Products (id, name, price, stock) values (71, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 8953964.21, 8267758);
insert into Products (id, name, price, stock) values (87, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 2580209.63, 6505722);
insert into Products (id, name, price, stock) values (3, 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', 4513074.93, 8585057);
insert into Products (id, name, price, stock) values (1, 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', 5692260.01, 9459392);
insert into Products (id, name, price, stock) values (39, 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 6460328.55, 6369250);
insert into Products (id, name, price, stock) values (32, 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', 6007552.55, 7017198);
insert into Products (id, name, price, stock) values (36, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id', 7351347.32, 8211392);
insert into Products (id, name, price, stock) values (72, 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus', 7147687.46, 9319772);
insert into Products (id, name, price, stock) values (71, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 837981.36, 8296565);
insert into Products (id, name, price, stock) values (65, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 6827149.74, 8968185);
insert into Products (id, name, price, stock) values (59, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 7793121.64, 1707910);
insert into Products (id, name, price, stock) values (80, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 9151420.84, 1529433);
insert into Products (id, name, price, stock) values (12, 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim', 1348145.99, 7587341);
insert into Products (id, name, price, stock) values (25, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 6742892.72, 3626058);
insert into Products (id, name, price, stock) values (54, 'convallis morbi odio odio elementum eu interdum eu tincidunt in', 9174927.41, 3969825);
insert into Products (id, name, price, stock) values (51, 'et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', 3943679.87, 4613258);
insert into Products (id, name, price, stock) values (77, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 3892065.86, 9929775);
insert into Products (id, name, price, stock) values (77, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', 8355273.79, 1702499);
insert into Products (id, name, price, stock) values (72, 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst', 8718635.61, 781538);
insert into Products (id, name, price, stock) values (90, 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 4432580.84, 3415749);
insert into Products (id, name, price, stock) values (30, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget', 3907311.96, 6050844);
insert into Products (id, name, price, stock) values (38, 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum', 1448620.89, 1108319);
insert into Products (id, name, price, stock) values (49, 'est phasellus sit amet erat nulla tempus vivamus in felis eu', 2098154.99, 1101943);
insert into Products (id, name, price, stock) values (92, 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in', 7666433.78, 2621944);
insert into Products (id, name, price, stock) values (50, 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 3275280.41, 7842328);
insert into Products (id, name, price, stock) values (63, 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 4110934.09, 4298671);
insert into Products (id, name, price, stock) values (12, 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', 6975615.66, 2810758);
insert into Products (id, name, price, stock) values (26, 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius', 7388301.21, 7058125);
insert into Products (id, name, price, stock) values (44, 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula', 9757629.29, 1857345);
insert into Products (id, name, price, stock) values (89, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 8103394.79, 2004549);
insert into Products (id, name, price, stock) values (91, 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit', 4496366.34, 9133686);
insert into Products (id, name, price, stock) values (55, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', 8408380.53, 9046218);
insert into Products (id, name, price, stock) values (18, 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 899340.72, 2978161);
insert into Products (id, name, price, stock) values (72, 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt', 8089125.84, 1581136);
insert into Products (id, name, price, stock) values (40, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', 9497244.58, 7552409);
insert into Products (id, name, price, stock) values (22, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc', 9611504.9, 776172);
insert into Products (id, name, price, stock) values (100, 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac', 2010492.36, 3727540);
insert into Products (id, name, price, stock) values (33, 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', 6247472.68, 2083051);
insert into Products (id, name, price, stock) values (89, 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 8994674.23, 2350193);
